### ISSUE TITLE
As a player, I want to see a better welcome screen with nice background and beautiful game title.

### ISSUE THREAD

**Issue by DuyKhau** [DuyKhau/ADP_Asignment5#21]

**Comment by TaoKhongPhaiLaMinh** [comment]
5: Cách để có 1 màn hình chào đón rực rỡ hơn và tựa game:
_ thiết kế background
_ thiết kế tựa game
_ nghiên cứu cách chèn hình
_ chèn hình và tựa đề vào ứng dụng
